name: Android Build

on:
  push:
    branches:
      - main # یا هر شاخه‌ای که می‌خواهید
  pull_request:
    branches:
      - main # یا هر شاخه‌ای که می‌خواهید

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' # یا نسخه‌ای که شما استفاده می‌کنید
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive APK
        if: success()
        run: |
          mkdir -p output
          cp app/build/outputs/apk/debug/app-debug.apk output/
          
      - name: Upload APK
        uses: actions/upload-artifact@v3 # به‌روزرسانی به نسخه 3
        with:
          name: app-debug.apk
          path: output/app-debug.apk
